/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 mug-draco.glb 
*/

import React, { useEffect, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import {Decal, ContactShadows, Environment,OrbitControls } from "@react-three/drei"
import { degToRad } from 'three/src/math/MathUtils.js';
import { TextureLoader } from "three"


export function Mug({texture}) {
  const textureuv = new TextureLoader().load('uvmap.jpeg' );
  textureuv.flipY = false; // Flip the texture vertically 
  console.log(texture)
  const { nodes, materials } = useGLTF('mug-draco.glb')
  const [mugTexture,setMugTexture]=useState(null);
  // texture.flipY = false;
  // Check if the geometry has UVs
if (nodes.Cylinder002_1_2.geometry.attributes.uv) {
  console.log("The mesh has UV mapping.");
} else {
  console.log("The mesh does not have UV mapping.");
}
  useEffect(()=>{

    if(texture){
      texture.flipY = false;
      setMugTexture(texture);
    }
  },[texture])
  return (
    <group dispose={null}>
      <group position={[21.036, 0, -23.02]}>
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['02___Default']} />
        <mesh geometry={nodes.Cylinder002_1_1.geometry} material={materials['08___Default']} />
        <mesh geometry={nodes.Cylinder002_1_2.geometry}  position={[0, 0.01, 0]}>
        <meshBasicMaterial transparent opacity={0} />
        {/* <Decal
          debug // Makes "bounding box" of the decal visible
          position={[-0.5,20.8,20.5]} // Position of the decal
          rotation={[degToRad(0),degToRad(90),degToRad(0)]} // Rotation of the decal (can be a vector or a degree in radians)
          scale={[65.5,30.5,65.5]} // Scale of the decal
        > */}
          <meshStandardMaterial
            map={textureuv}
            flipY={false} // Try this if the texture appears flipped
            toneMapped={false}
            transparent
            polygonOffset
            polygonOffsetFactor={-1} // The mesh should take precedence over the original
          />
        {/* </Decal> */}
          {/* toggling these two below words  */}
          {/* <meshBasicMaterial 
          map={texture} 
          opacity={1} 
          polygonOffset 
          // roughness={0.5} // Adjust material properties as needed
          //    metalness={0.1} // Adjust as per your needs
          polygonOffsetFactor={-1} 
          polygonOffsetUnits={1} /> */}
          {/* <meshStandardMaterial 
          position={[0, 0.01, 0]}
          transparent
             map={mugTexture} // Apply the texture from fabric.js
             roughness={0.5} // Adjust material properties as needed
             metalness={0.1} // Adjust as per your needs
            //  opacity={1} // Ensure full opacity
             polygonOffset 
             polygonOffsetFactor={-1} 
          polygonOffsetUnits={1}
          /> */}
        
        </mesh>
      </group>
      <group position={[21.311, 1.513, -23.561]}>
        <mesh geometry={nodes.Arc002_1.geometry} material={materials['08___Default-2']} />
        <mesh geometry={nodes.Arc002_1_1.geometry} material={materials['02___Default-2']} />
      </group>
    </group>
  )
}

